### ISSUE TITLE
Supported still?

### ISSUE THREAD

**Issue by ghost** [timjong93/MMM-MPD#10]
Any chance of getting this module working again? I've installed, added to my config and it never actually shows on my magicmirror, tried all the advace from the other issues and nothing. I see it hasn't been worked on since 2018 but i'd be nice to get this module working again.. And yes i've tried 'coderpussy' fork but that's a no go either, plus it doesn't say it's had any changed from the main branch so idk?

**Comment by Waldehead** [comment]
The problem is that Coderpussy's pull request is just a request. 
For me worked the following workaround.

At first switch to your modules folder and remove the MPD-Module, then clone the repository from coderpussy via
`git clone https://github.com/coderpussy/MMM-MPD/ -b develop ./MMM-MPD/`
(i think you can remove the "./MMM-MPD/", but i didn't try it)
After this:
```
cd ./MMM-MPD
npm install
```
It says something like 
```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN mmm_mpd_client@0.1.0 No repository field.
npm WARN mmm_mpd_client@0.1.0 license should be a valid SPDX license expression

added 1 package from 1 contributor and audited 1 package in 1.996s
found 0 vulnerabilities
```

And last but not least edit your config like
```
{
		module: "MMM-MPD",
		position: "top_right",	// This can be any of the regions.
		config: {
			// See 'Configuration options' for more information.
			hostname: "localhost",
			port: 6600
			
		}
	}
```
And that's how it looks like on my MagicMirror
![image](https://user-images.githubusercontent.com/46871020/107030510-0d99fd00-67b1-11eb-943b-82e67c588f28.png)


I hope i could help :)


EDIT:
Just saw that Coderpussy opened her own repository for it, it works for me too.
There is the readme correct, so maybe try this
https://github.com/coderpussy/MMM-Mopidy-MPD
https://github.com/coderpussy/MMM-Mopidy-MPD

**Comment by coderpussy** [comment]
@Waldehead you couldn't better explain the pain. Many thx to you. <3

**Comment by ghost** [comment]
@Waldehead Sweet that solved it for me, Everything seems to be working now. Thanks!
